sonar.organization=felipeschirmann
sonar.projectKey=felipeschirmann_DSVendas
sonar.projectName=DSVendas
sonar.host.url=https://sonarcloud.io

# Define sources, tests and exclusions
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/**/*.test.tsx,frontend/src/**/*.test.ts,frontend/src/setupTests.ts
sonar.exclusions=frontend/node_modules/**,frontend/build/**,**/target/**,frontend/src/**/*.test.tsx,frontend/src/**/*.test.ts,frontend/src/setupTests.ts

# Java specific configuration
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Code coverage exclusions
sonar.coverage.exclusions=backend/src/main/java/com/devsuperior/dsvendas/config/**,backend/src/main/java/com/devsuperior/dsvendas/dto/**,backend/src/main/java/com/devsuperior/dsvendas/entities/**,backend/src/main/java/com/devsuperior/dsvendas/DsvendasApplication.java,backend/src/main/java/com/devsuperior/dsvendas/ServletInitializer.java

# JavaScript/TypeScript coverage report path
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
