sonar.organization=felipeschirmann
sonar.projectKey=felipeschirmann_DSVendas
sonar.projectName=DSVendas
sonar.host.url=https://sonarcloud.io

# Define sources and exclusions
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java
sonar.exclusions=frontend/node_modules/**,frontend/build/**,**/target/**

# Java specific configuration
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
